global:
  containerRegistry: ghcr.io/airyhq
config:
  kafka:
    brokers: "kafka-headless:9092"
    zookeepers: "zookeeper:2181"
    schemaRegistryUrl: "http://schema-registry:8081"
    commitInterval: 1000
provisioning:
  kafka:
    image: ghcr.io/airyhq/infrastructure/kafka
    imageTag: 2.7.0
