apiVersion: v1
kind: ConfigMap
metadata:
  name: security
data:
  {{- if .Values.global.security.systemToken }}
  systemToken: {{ .Values.global.security.systemToken | quote }}
  {{- end }}
  jwtSecret: {{ .Values.global.security.jwtSecret | quote }}
  allowedOrigins: {{ .Values.global.security.allowedOrigins | quote }}
---
{{- define "host" }}
{{- if .Values.global.ingress }}
  {{- if .Values.global.ingress.https }}
    {{- printf "https://%s" .Values.global.kubernetes.host }}
  {{- else }}
    {{- printf "http://%s" .Values.global.kubernetes.host }}
  {{- end }}
{{- else }}
  {{- printf "http://%s" .Values.global.kubernetes.host }}
{{- end }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
data:
  APP_IMAGE_TAG: {{ .Values.global.kubernetes.appImageTag }}
  CORE_ID: {{ randAlphaNum 10 | lower }}
  CHATPLUGIN_JWT_SECRET: {{ randAlphaNum 128 | quote }}
  API_HOST: {{ template "host" . }}
  HOST: {{ template "host" . }}