apiVersion: v1
kind: ConfigMap
metadata:
  name: security
data:
  {{- if .Values.security.systemToken }}
  systemToken: {{ .Values.security.systemToken | quote }}
  {{- end }}
  jwtSecret: {{ .Values.security.jwtSecret | quote }}
  allowedOrigins: {{ .Values.security.allowedOrigins | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
data:
  APP_IMAGE_TAG: {{ .Values.global.appImageTag }}
  CORE_ID: {{ randAlphaNum 10 | lower }}
  CHATPLUGIN_JWT_SECRET: {{ randAlphaNum 128 | quote }}
  {{- if .Values.ingress.host }}
  API_HOST: {{ default "http://airy.core" .Values.ingress.host }}
  {{- end }}
